# Generated by Django 4.2.1 on 2023-05-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_agent_listing_ad_status_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ad_status',
            field=models.CharField(choices=[('Продажа', 'Продажа'), ('Аренда', 'Аренда')], default='Продажа', max_length=10),
        ),
    ]
